export const MERCHANT_ERRORS = {
  NOT_FOUND: 'MERCHANT_NOT_FOUND',
  ALREADY_EXISTS: 'MERCHANT_ALREADY_EXISTS',
  DUPLICATE_GST: 'DUPLICATE_GST',
  DUPLICATE_PAN: 'DUPLICATE_PAN',
  NOT_VERIFIED: 'MERCHANT_NOT_VERIFIED',
  KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',
  KYC_NOT_FOUND: 'KYC_NOT_FOUND',
  KYC_ALREADY_VERIFIED: 'KYC_ALREADY_VERIFIED',
  TEAM_MEMBER_EXISTS: 'TEAM_MEMBER_EXISTS',
  TEAM_MEMBER_NOT_FOUND: 'TEAM_MEMBER_NOT_FOUND',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  BANK_NOT_FOUND: 'BANK_NOT_FOUND',
  BANK_LIMIT_REACHED: 'BANK_LIMIT_REACHED',
  INSUFFICIENT_PERMISSION: 'INSUFFICIENT_PERMISSION',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
} as const;

export const MERCHANT_TEAM_ROLES_KEY = 'merchantTeamRoles';

export const MERCHANT_EVENTS = {
  REGISTERED: 'merchant.registered',
  UPDATED: 'merchant.updated',
  APPROVED: 'merchant.approved',
  REJECTED: 'merchant.rejected',
  KYC_UPLOADED: 'merchant.kyc.uploaded',
  BANK_ADDED: 'merchant.bank.added',
  TEAM_INVITED: 'merchant.team.invited',
  TEAM_MEMBER_UPDATED: 'merchant.team.member_updated',
  TEAM_MEMBER_REMOVED: 'merchant.team.member_removed',
} as const;

export const DOCUMENT_STORAGE = {
  BASE_PATH: 'merchant',
  DOCUMENTS_PATH: 'merchant/documents',
  LOGOS_PATH: 'merchant/logos',
  ALLOWED_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  MAX_FILE_SIZE: 10 * 1024 * 1024,
} as const;

export const MERCHANT_CONSTANTS = {
  MAX_BANK_ACCOUNTS: 5,
  MAX_TEAM_MEMBERS: 20,
  INVITATION_EXPIRY_HOURS: 48,
} as const;
