-- AlterTable
ALTER TABLE `campaign_tasks` MODIFY `taskType` ENUM('SCREENSHOT', 'URL', 'VIDEO', 'TEXT', 'FILE_UPLOAD', 'CUSTOM', 'INSTAGRAM_FOLLOW', 'INSTAGRAM_LIKE', 'INSTAGRAM_COMMENT', 'INSTAGRAM_STORY_SHARE', 'FACEBOOK_SHARE', 'FACEBOOK_LIKE', 'GOOGLE_REVIEW', 'PLAY_STORE_REVIEW', 'APP_INSTALL', 'REFERRAL', 'SURVEY', 'WEBSITE_VISIT', 'WATCH_VIDEO', 'YOUTUBE_SUBSCRIBE', 'TWITTER_FOLLOW', 'QR_SCAN', 'LOCATION_CHECKIN') NOT NULL,
    MODIFY `proofType` ENUM('SCREENSHOT', 'VIDEO', 'URL', 'TEXT', 'METADATA', 'QR_CODE', 'LOCATION') NULL;

-- AlterTable
ALTER TABLE `merchants` ADD COLUMN `latitude` DOUBLE NULL,
    ADD COLUMN `longitude` DOUBLE NULL;

-- AlterTable
ALTER TABLE `task_submissions` MODIFY `verificationSource` ENUM('AI', 'MANUAL', 'HYBRID', 'SYSTEM') NOT NULL DEFAULT 'AI';
