const STATUS_COLOR_MAP: Record<string, string> = {
  ACTIVE: 'badge-green',
  APPROVED: 'badge-green',
  VERIFIED: 'badge-green',
  SUCCESS: 'badge-green',
  COMPLETED: 'badge-green',
  PAID: 'badge-green',
  CREDITED: 'badge-green',
  PUBLISHED: 'badge-green',
  RESOLVED: 'badge-green',
  PENDING: 'badge-yellow',
  PENDING_VERIFICATION: 'badge-yellow',
  PENDING_REVIEW: 'badge-yellow',
  PENDING_MANUAL: 'badge-yellow',
  UNDER_REVIEW: 'badge-yellow',
  AI_PROCESSING: 'badge-yellow',
  PROCESSING: 'badge-yellow',
  MEDIUM: 'badge-yellow',
  CHANGES_REQUESTED: 'badge-yellow',
  ASSIGNED: 'badge-yellow',
  IN_PROGRESS: 'badge-yellow',
  REQUIRES_RESUBMISSION: 'badge-yellow',
  SCHEDULED: 'badge-blue',
  OPEN: 'badge-blue',
  DRAFT: 'badge-gray',
  PAUSED: 'badge-gray',
  LOW: 'badge-gray',
  CANCELLED: 'badge-gray',
  EXPIRED: 'badge-gray',
  DEACTIVATED: 'badge-gray',
  ARCHIVED: 'badge-gray',
  CLOSED: 'badge-gray',
  NOT_SUBMITTED: 'badge-gray',
  SUSPENDED: 'badge-red',
  REJECTED: 'badge-red',
  FAILED: 'badge-red',
  BANNED: 'badge-red',
  CRITICAL: 'badge-red',
  HIGH: 'badge-red',
  WAITING_USER: 'badge-purple',
}

export function getStatusColor(status: string): string {
  return STATUS_COLOR_MAP[status] ?? 'badge-gray'
}
