-- AlterTable
ALTER TABLE `referral_rewards` MODIFY `status` ENUM('PENDING', 'APPROVED', 'CREDITED', 'FAILED', 'CANCELLED', 'EXPIRED', 'REVERSED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `rewards` ADD COLUMN `reversalReason` TEXT NULL,
    ADD COLUMN `reversedAmount` DECIMAL(12, 2) NULL,
    ADD COLUMN `reversedAt` DATETIME(3) NULL,
    ADD COLUMN `reversedBy` VARCHAR(191) NULL,
    ADD COLUMN `shortfallAmount` DECIMAL(12, 2) NULL,
    MODIFY `status` ENUM('PENDING', 'APPROVED', 'CREDITED', 'FAILED', 'CANCELLED', 'EXPIRED', 'REVERSED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `wallet_transactions` MODIFY `type` ENUM('CREDIT', 'DEBIT', 'HOLD', 'RELEASE', 'REFUND', 'WITHDRAWAL', 'BONUS', 'REFERRAL', 'SPEND', 'CLAWBACK') NOT NULL;
